CREATE TABLE dcuser (
    n_id SERIAL PRIMARY KEY,
	N_CODUSER VARCHAR NOT NULL,
    C_NOMUSER VARCHAR NOT NULL,
	C_ESTPER  VARCHAR NOT NULL CHECK (C_ESTPER IN ('P', 'D')),
	C_ESTREG CHAR CHECK (C_ESTREG IN ('S', 'N')) DEFAULT 'S',
    T_CREATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);